# Generated by Django 3.0.5 on 2020-05-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('notes_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=50000)),
            ],
        ),
    ]
